#!/bin/bash
### BEGIN INIT INFO
# Provides:          updatePackagesStatus
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: updatePackagesStatus
# Description:       updatePackagesStatus
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin:REPLACELBHOMEDIR/bin"
PATH=$PATH.":REPLACELBHOMEDIR/sbin"

if [ -e /usr/share/rpimonitor/scripts/updatePackagesStatus.pl ]
then
 /usr/share/rpimonitor/scripts/updatePackagesStatus.pl
fi

exit 0
