#!/bin/sh
### BEGIN INIT INFO
# Provides:          RPi-Monitor
# Required-Start:    $remote_fs $syslog $network 
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This file starts the Loxberry RPi-Monitor update
# Description:       This file starts the Loxberry RPi-Monitor update.
### END INIT INFO

. /lib/lsb/init-functions

### END INIT INFO

# Version 1.1
# 15.09.2016 15:14:00

if [ -f REPLACEBYPATHTODATA/doinstall ]
	then
    log_action_msg "Fresh installation. Installing RPiMonitor package"
    dpkg -i REPLACEBYPATHTODATA/rpimonitor_latest_all.deb
    cp REPLACEBYPATHTODATA/data.conf /etc/rpimonitor/
    cp REPLACEBYPATHTODATA/version.conf /etc/rpimonitor/template/
    rm REPLACEBYPATHTODATA/doinstall
	fi

/etc/init.d/rpimonitor install_auto_package_status_update
exit 0
